### ISSUE TITLE
Auctionator prices

### ISSUE THREAD

**Issue by Thelion987** [Eliote/AutoLooter#2]
I made a small Tweak to your code to add Auctionator prices to the loot rule. 

If you want to use this, please do.  Link to the changed code:
https://github.com/Thelion987/AutoLooter

**Comment by Eliote** [comment]
This can probably be a module for AutoLooter, in its on AddOn. That way you can depend on both addons in the toc file. (AutoLooter and Auctionator)

This module is a nice example: https://github.com/Eliote/AutoLooter/blob/master/modules/FishingIgnore.lua
I exposed the `ToggleableModulePrototype` in `AutoLooter.ToggleableModulePrototype` in the last version.
So you can create a module with: 
`local module = AutoLooter:NewModule("FishingIgnore", AutoLooter.ToggleableModulePrototype)`

**Comment by Thelion987** [comment]
Thanks, for the advise!  I will do that when i have some time.
