### ISSUE TITLE
Bug in addon

### ISSUE THREAD

**Issue by shielddz** [Eliote/AutoLooter#3]
I had a bug causing the game to crash over and over, once it didn't I caught this error message :

[string "@AutoLooter/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <AutoLooter/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@AutoLooter/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@AutoLooter/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <AutoLooter/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

**Comment by Eliote** [comment]
Does this happens with only AutoLooter enabled?
Since the error is happening in a lib, it's probably AutoLooter being blamed for another addon problem just because it's lib was loaded first.

**Comment by shielddz** [comment]
Indeed it was with autoturnIn. I'm not familiar with wow addons bug stack soz, so could you tell me how I can provide further info?

**Comment by Eliote** [comment]
You should report it to the autoturnIn Author.
